# Generated by Django 5.2.7 on 2025-11-22 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='productsapp.rubro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='productsapp.category'),
        ),
    ]
